CREATE TABLE IF NOT EXISTS MEDICAL_DATA_VAULT.RAW_DATA_VAULT.RAW_CLIENT_INPUT_METADATA (
    BATCH_ID VARCHAR(36),
    CLIENT_NAME VARCHAR(255),
    FILE_NAME VARCHAR(255),
    FILE_FORMAT VARCHAR(30),
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PROCESSING_STATUS INTEGER DEFAULT 0,
    PRIMARY KEY (BATCH_ID)
);

CREATE TABLE IF NOT EXISTS MEDICAL_DATA_VAULT.RAW_DATA_VAULT.RAW_CLIENT_INPUT_DATA (
    BATCH_ID VARCHAR(36),
    RAW_DATA VARIANT,
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (BATCH_ID) REFERENCES MEDICAL_DATA_VAULT.RAW_DATA_VAULT.RAW_CLIENT_INPUT_METADATA(BATCH_ID)
    
) CLUSTER BY (BATCH_ID);


